# .github/workflows/build_firmware.yml
name: Reusable Build Firmware

on:
  workflow_call:
    inputs:
      platform:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Cache PlatformIO
        uses: actions/cache@v4
        with:
          path: ~/.platformio
          key: ${{ runner.os }}-platformio-${{ inputs.platform }}-${{ hashFiles('**/platformio.ini', '**/lib_deps/*') }}
          restore-keys: |
            ${{ runner.os }}-platformio-${{ inputs.platform }}-
      - name: Cache PlatformIO Build Directory
        uses: actions/cache@v4
        with:
          path: .pio
          key: ${{ runner.os }}-pio-${{ inputs.platform }}-${{ hashFiles('**/platformio.ini', '**/lib_deps/*') }}
          restore-keys: |
            ${{ runner.os }}-pio-${{ inputs.platform }}-
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
      - name: Install PlatformIO
        run: pip install platformio
      - name: Build file system image for ${{ inputs.platform }}
        run: pio run --target buildfs -e ${{ inputs.platform }} 
      - name: Build for ${{ inputs.platform }}
        run: pio run -e ${{ inputs.platform }} -t mergebin
      #- name: Display firmware files
      #  run: ls -la .pio/build/${{ inputs.platform }}/firmware*.bin
      - name: Rename and move firmware files
        run: |
          mv .pio/build/${{ inputs.platform }}/firmware.bin firmware_${{ inputs.platform }}_ota.bin
          if [ "${{ inputs.platform }}" != "esp8266dev" ]; then
            mv .pio/build/${{ inputs.platform }}/firmware_factory.bin firmware_${{ inputs.platform }}_factory.bin
          fi
          ls -la firmware*.bin
      - name: Archive Firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware_${{ inputs.platform }}
          path: firmware_${{ inputs.platform }}*.bin
